# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 239d64b66758a050d26bc703c5f64f6f4af465287dd94bb0509558a5a7419d70e4601e4f5e95c38a114c8e4d1961d38f687a43315502486f9fcea98923a5a3c0

test:
  secret_key_base: 4419cef94a1c9e4bb78a65f215c71c1d076dce6c07054827fe857a5ee030ccafee10364ac3b17b1798b615840025aef3171eb2353df2d1ef721f78f5b73c3f44

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
